#define I2C_SCL 15
#define I2C_SDA 16
#define PIN_VBAT_READ    17
#define AREF_VOLTAGE            (3.0)
#define ADC_MULTIPLIER (1.509F)
#define PIN_BUZZER 5
#define PIN_VEXT_EN_ACTIVE HIGH
#define PIN_VEXT_EN 46
#define PIN_USER_BTN 47
#define PIN_LED 6
#define PIN_STATUS_LED 6
#define PIN_PWRBTN 4
