[GAT562_Mesh_EVB_Pro]
extends = nrf52_base
board = rak4631
board_check = true
build_flags = ${nrf52_base.build_flags}
  ${sensor_base.build_flags}
  -I variants/gat562_mesh_evb_pro
  -D NRF52_POWER_MANAGEMENT
  -D PIN_BOARD_SCL=14
  -D PIN_BOARD_SDA=13
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<../variants/gat562_mesh_evb_pro>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/sensors>
lib_deps =
  ${nrf52_base.lib_deps}
  ${sensor_base.lib_deps}
  sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.27

[env:GAT562_Mesh_EVB_Pro_repeater]
extends = GAT562_Mesh_EVB_Pro
build_flags =
  ${GAT562_Mesh_EVB_Pro.build_flags}
  -D ADVERT_NAME='"GAT562 EVB Pro Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${GAT562_Mesh_EVB_Pro.build_src_filter}
  +<../examples/simple_repeater>


[env:GAT562_Mesh_EVB_Pro_room_server]
extends = GAT562_Mesh_EVB_Pro
build_flags =
  ${GAT562_Mesh_EVB_Pro.build_flags}
  -D ADVERT_NAME='"GAT562 EVB Pro Room Server"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${GAT562_Mesh_EVB_Pro.build_src_filter}
  +<../examples/simple_room_server>

[env:GAT562_Mesh_EVB_Pro_kiss_modem]
extends = GAT562_Mesh_EVB_Pro
build_src_filter = ${GAT562_Mesh_EVB_Pro.build_src_filter}
  +<../examples/kiss_modem/>
